### ISSUE TITLE
Style of <h4> on mobile devices

### ISSUE THREAD

**Issue by mbruellmann** [swiss/styleguide#266]
```html
<h1 class="title"><span></span>Livre deuxième: Droit de la famille</h1>
<h2 class="title"><span></span>Première partie: Des époux</h2>
<h2 class="title"><span></span>Deuxième partie: Des parents</h2>
<h3 class="title"><span></span>Titre septième: De l'établissement de la filiation</h3>
<h4 class="title"><span></span>Chapitre premier: Dispositions générales</h4>
```

![issue webdesign bund h4](https://cloud.githubusercontent.com/assets/7466385/4659964/d510c250-5512-11e4-8146-800f62e47a59.png)

Dans les versions autres que plein écran, le niveau de titre H4 (ici Chapitre premier) paraît visuellement être supérieur au niveau H3 (ici Titre septième).
Adapter selon l'affichage plein écran.

**Comment by tonifisler** [comment]
We can't test with these `+` `-` collapsibles because they are not part of the styleguide. 

However, we set the titles to display this way on mobile:

![ios simulator screen shot 19 jan 2015 12 06 16](https://cloud.githubusercontent.com/assets/1708450/5799551/cf84a994-9fd3-11e4-8dc4-13adb1027d77.png)

**Comment by zufrieden** [comment]
rewieved
