### ISSUE TITLE
Missing print function in contact box

### ISSUE THREAD

**Issue by LukasJaborsky** [swiss/styleguide#357]
We are missing the print 	functionality behind the print button in the contact-box. This feature was already included in the old webguidelines. 

Is it not implemented or are we not able to see it? 

Thanks for your help.

**Comment by zufrieden** [comment]
We didn't implement this feature. I'll ask the Chancellerie.

**Comment by desobryc** [comment]
![image](https://cloud.githubusercontent.com/assets/7644740/9324194/4d8d35cc-4588-11e5-9940-12331fb2cc51.png)
the print function is still missing for the "map" part of the contact box 

+ when I choose the option "links as footnotes", the display is adapting but the links are missing at the end of the page, is it a bug or it is just because they are fake links?
![image](https://cloud.githubusercontent.com/assets/7644740/9324232/adeed27c-4588-11e5-8fd0-485e95575bbf.png)

+ it is not working properly on IE9
![image](https://cloud.githubusercontent.com/assets/7644740/9324244/c4acb88a-4588-11e5-98ad-6baa03161566.png)

**Comment by desobryc** [comment]
The function "links as footnotes" isn't displaying anything on IE9 + shouldn't the urls only be displayed when the function "links as footnotes" is active? 

![image](https://cloud.githubusercontent.com/assets/7644740/9379001/68e49ab4-4726-11e5-9799-139b69dbeea7.png)

**Comment by tonifisler** [comment]
The function is working on my side. Note that we don't display any footnote if the URL doesn't start with `http://`. We did this to avoid a footer bloated with `#` links.

We'll add a clear comment about this in the docs.

**Comment by desobryc** [comment]
Will be solved with SWG-80

**Comment by LeBenLeBen** [comment]
This issue has been addressed in version 3.0.0.
