### ISSUE TITLE
".table-striped" class does not render a striped table

### ISSUE THREAD

**Issue by ift-jsy** [swiss/styleguide#358]
Hello,

I just found out that the ".table-striped" have a wrong rendering:
![table_striped](https://cloud.githubusercontent.com/assets/11071351/6327024/d7807552-bb57-11e4-825b-72c5a618563e.png)

I supposed that the problem come for those two selectors:

table-striped>tbody>tr:nth-of-type(odd) {
   background-color: #f9f9f9;
}

.table-striped>tbody>tr:nth-child(even)>td, .table-striped>tbody>tr:nth-child(even)>th {
background-color: #f9f9f9;
}

The first set a background for the odd rows and the second set a background for all the cells of the even rows which finally give a background for the whole table. Deactivating one of them fix the rendering:
![table_striped_without_td](https://cloud.githubusercontent.com/assets/11071351/6327118/b028ee02-bb58-11e4-9bd0-f779d1d40716.png)
![table_striped_without_tr](https://cloud.githubusercontent.com/assets/11071351/6327119/b0293308-bb58-11e4-9cab-4549bc976413.png)

**Comment by tonifisler** [comment]
The bug is happening because of this PR from Bootstrap: https://github.com/twbs/bootstrap/pull/13920

We can resolve this by changing https://github.com/swiss/styleguide/blob/master/assets/sass/layout/tables.scss#L212-L230 to:

```scss
.table-striped {
  > tbody > tr:nth-of-type(odd) {
    background-color: transparent;
  }
  > tbody > tr:nth-of-type(even) {
    background-color: $table-bg-accent;
  }
  > thead td, > thead th, > tfoot td, > tfoot th {
    background: $smoke;
    font-weight: 700;
    color: $black;
  }
}
```

Use `:nth-of-type` to be consistent with a change from v3.3.2 regarding tooltips https://github.com/twbs/bootstrap/pull/15551
