### ISSUE TITLE
Forms - Date Input Field: Date Picker doesn't work in IE and Firefox

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#379]
Field type=date isn't supported by all browsers. In such a case, the input field is treated like a normal text field and the user doesn't get any support when entering a date. We discovered this behaviour with Internet Explorer 11 and Firefox 38.

![image](https://cloud.githubusercontent.com/assets/9591815/9129581/f6ce552e-3cd9-11e5-9467-d69df48c3cde.png)

**Comment by tonifisler** [comment]
Some browsers support the `<input type="date" />` and add a calendar, some don't. The only way to be sure to have a calendar view is to add an optional JS plugin.

**Comment by Yago** [comment]
So, we have investigate to find the better JavaScript library to fits with your need and that keep good accessibility and we select [jQueryUI's datepicker module](https://jqueryui.com/datepicker/) and [Pikaday](http://dbushell.github.io/Pikaday/). Both will work with a simple `<input type="date">` without any hack, will be easy to fit to the Swiss design guidelines and will be applied only on desktop version, because the native iOS/Android works pretty well. Pikaday seems to be the best option, because he is four time lighter that jQueryUI and developed in a moderner mindset.

Now, our question is : did you really need a JavaScript library for date inputs ? Basically, the `<input type="date">` will be take in charge by browser. Some like Chrome, Safari iOS, Androir Browser offering datepicker, some other like Firefox or Safari let user type there date like if it's a classic text input. Using a library offer in any case the datepicker, but constrains also to a specific date format, here YYYY-MM-DD (ex: 2015-10-07). It can be a good thing if you want to unify the data you want to get, but can be a bit inflexible in some case.

We creat an example that let you test and take the better decision. We don't tell you that using a JavaScript datepicker is evil, we just have to be sure that all the issues are clear on your side.

Test version : [Codepen debug](http://s.codepen.io/Yago_0/debug/memQPb?)
Code version : [Codepen editable](http://codepen.io/Yago_0/pen/memQPb)

**Comment by desobryc** [comment]
Let's go for Pikaday as both versions are ok regarding functionality. But the native and pikaday shouldn't be both displayed as in the following example: 

![screen shot 2015-10-13 at 16 50 19](https://cloud.githubusercontent.com/assets/7644740/10485494/cf0e193e-728a-11e5-8558-52f204b1f387.png)

**Comment by ludovicrenevey** [comment]
@desobryc thank you for the reply. We start the work today on that issue and we are going to contact you as soon it is done.
