### ISSUE TITLE
Broader tables cover contact box

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#414]
If a table is too broad, it covers the contact box.

![tabelle_over_contact-column1](https://cloud.githubusercontent.com/assets/9591815/10688572/872461d6-7975-11e5-9364-1ca7dcf62269.png)
![tabelle_over_contact-column2](https://cloud.githubusercontent.com/assets/9591815/10688575/8b5ad53c-7975-11e5-81d0-ac5b3eb48343.png)

**Comment by tonifisler** [comment]
Thanks for reporting. :+1: 

This could be fixed with a rather awkward `word-break: break-all;` or with shorter headings :wink: 

The issue lies more in the fact that there are 3 columns, and this is not really optimal to display a lot of information.

A possible solution would be to wrap everything with `overflow-x: scroll;` or to implement something like [Tablesaw.js](https://github.com/filamentgroup/tablesaw) which comes with a horizontal sliding function with a proper behaviour on both desktop and mobile.

**Comment by desobryc** [comment]
https://jira.liip.ch/browse/SWG-106

**Comment by LeBenLeBen** [comment]
Bootstrap’ [responsive table](http://getbootstrap.com/css/#tables-responsive) component would be probably useful here.

**Comment by mbruellmann** [comment]
It looks to me as an editorial and not a technical problem. Editors should use shorter words; this is allways possible. Shorter words also make it easier for users to understand the content of a table.

**Comment by GS-VBS-Webteam** [comment]
It also a technical issue, because the content of some tables comes from API and other systems. For this reason, it has to be solved.

**Comment by GS-VBS-Webteam** [comment]
Kann dieses Issue im neuen Release (Milestone) übernommen werden ?

**Comment by mbruellmann** [comment]
Graciela und ihr Team schauen es an.

**Comment by bit-pro-iew-eui** [comment]
This is a known issue in the Web of non-breaking table cells and can be easily fixed using the Bootstrap's `.table-responsive` class in your implementation of the tables which grow broad.
