### ISSUE TITLE
Verdeckte Übersichtsseite im Responsive Design

### ISSUE THREAD

**Issue by GS-VBS-Webteam** [swiss/styleguide#494]
Die letzte Übersichtsseite ist im Responsive Design (auf iPhone) verdeckt. 

![uebersichtsseite_verdeckt](https://cloud.githubusercontent.com/assets/9591815/18479069/d7207440-79d3-11e6-9149-99835eeb9929.PNG)

**Comment by bit-pro-iew-eui** [comment]
@GS-VBS-Webteam the webguideline has not an element like this
## 
![image](https://cloud.githubusercontent.com/assets/7510842/22779339/ac67edda-eeba-11e6-91fe-796633b6c886.png)
## 
when you open the main navigation on an iPhone, it has the "< back" link. This issue is in your CMS implementation and not in the guideline. Please forward this issue to your provider.

## Screenshot of an iPhone when the main navigation is open.
![img_3388](https://cloud.githubusercontent.com/assets/7510842/22779517/65a9e2a8-eebb-11e6-91cf-98071876bc42.PNG)
