### ISSUE TITLE
Compatibility with web browser Edge needs to be ensured

### ISSUE THREAD

**Issue by Soardiac** [swiss/styleguide#501]
With APS 2020, Federal Administration will use Edge as the only web browser. The Webguidelines need to be compatible with Edge early so all CMS and applications can be made compatible using the latest WGL version.

**Comment by bit-pro-iew-eui** [comment]
There are these problems with the Edge Web Browser

- [ ] Expandable Table rows wrong height
 
https://swiss.github.io/styleguide/en/tables.html#03-tables-14-table-expandable
![image](https://user-images.githubusercontent.com/7510842/28211091-2097b000-689b-11e7-99b6-0863d931299f.png)

- [ ] Accessibility Links aren't shown
https://swiss.github.io/styleguide/en/header.html#02-header-02-accessibility-navigation

- [ ] Social sharing  and document icons are wrong displayed
https://swiss.github.io/styleguide/en/functions.html#04-functions-02-social-sharing
![image](https://user-images.githubusercontent.com/7510842/28211603-d80ea750-689d-11e7-81c0-05fd84fc0745.png)

**Comment by q-src** [comment]
> Accessibility Links aren't shown

Cannot reproduce this with MS Edge 20.10240.17146.0. 
I agree it behaves a bit differently than in Chrome and Firefox. The latter display the access links after the first tab press. In MS Edge it takes several tab presses. 
In fact, this behavior is neither correct nor wrong. It is due to the webguidelines using accessibility links themselves. These start with index 0, too. So in the end there are two accessibility links with index 0. In such a case, it is not defined which of them should be selected by the first tab press. So the browser has to make a choice itself. Whilst Chrome and Firefox prioritize the items in the current view port, MS Edge strictly follows a top down approach by prioritizing elements by their position on the whole page.

In order to produce the same behavior on all browsers, there are two options:
* Change the accessibility indexes of the webguidelines. However, this would drastically decrease the webguidelines' accessibility, as these links would no longer be the first selectable by keyboard.
* Change the accessibility indexes of the example. However, one could think that accessbility link indexes should start at 3, which is even worse. Even if we'd document this, most people will just do copy+paste an therefore use wrong code on their web page.

So I suggest to not change the code and add a note to the accessibility link example, telling the reader that in some browsers the example links don't get displayed after the first tab press.

**Comment by q-src** [comment]
Cannot reproduce the print / document icon issues with MS Edge 20.10240.17146.0. Maybe there was a bug in an earlier version of MS Edge. Which version did you use when you took the screenshots?

The missing social sharing icon issue happens in all browsers but only on github.io (See also #529). I will have a look at this.
