### ISSUE TITLE
Hover over links in IE: Remove underline on preceding icons

### ISSUE THREAD

**Issue by ccweb** [swiss/styleguide#503]
When hovering over a link, the preceding icon is underlined in IE. In other browsers the behavior (Firefox, Chrome, Opera) is correct, i.e. only the link is underlined but not the icon.

e.g. https://swiss.github.io/styleguide/en/typography.html#04-typography-09-top-link
![hover-text-decoration](https://cloud.githubusercontent.com/assets/7446943/22060940/20374336-dd73-11e6-81f0-4ba8be67a793.png)

**Comment by LeBenLeBen** [comment]
Please precise which version of IE if you can. Thanks

**Comment by ccweb** [comment]
IE version
![ie-version](https://cloud.githubusercontent.com/assets/7446943/22062413/d5bb8176-dd79-11e6-9aed-5077a5b49473.png)

**Comment by janissbinder** [comment]
I am not able to fix this issue in a simple way. Its a IE only bug for pseude Element styling. 

The current implementation looks like this: 
`<a href="#" class="icon icon--before icon--power">Back to top</a>`
That I'm able to style this, I have to create a span element only for the text like this: 
`<a href="#" class="icon icon--before icon--power"><span>Back to top</span></a>`

This means I have to change every link in the whole project. I think the effort to fix this issue is way to high for such a little styling bug which doesn't affect a lot of people. @bit-pro-iew-eui Please assess if I really should fix it.

**Comment by almeidap** [comment]
@janissbinder Did you try the solution described here: https://stackoverflow.com/a/8820459

**Comment by janissbinder** [comment]
@almeidap It's unfortunately already styled like this

**Comment by gillerr** [comment]
Won't fix
